// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       int32
	Email    string
	Username string
	Bio      pgtype.Text
	Image    pgtype.Text
}

type UserPassword struct {
	UserID   pgtype.Int4
	Password string
}

type UserSession struct {
	UserID       pgtype.Int4
	SessionToken string
}
