// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import ()

type User struct {
	ID       interface{}
	Email    string
	Username string
	Password string
	Bio      string
	Image    string
}
